// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDZ5LY7J9dbhL7y3KPHI5hBOBW7ovLM3sU',
    appId: '1:100194839456:web:361462551dd86213f292c5',
    messagingSenderId: '100194839456',
    projectId: 'iste-528bd',
    authDomain: 'iste-528bd.firebaseapp.com',
    storageBucket: 'iste-528bd.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBA5J0TQ4y1pCdIHhG3iCMXkokzgaFAFho',
    appId: '1:100194839456:android:42de9db81f582c8ef292c5',
    messagingSenderId: '100194839456',
    projectId: 'iste-528bd',
    storageBucket: 'iste-528bd.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB0FSn8AalyOsUE5tHmRnXywyTA9xHpNvQ',
    appId: '1:100194839456:ios:85f3eefcc04d750af292c5',
    messagingSenderId: '100194839456',
    projectId: 'iste-528bd',
    storageBucket: 'iste-528bd.firebasestorage.app',
    iosBundleId: 'com.example.isteMbcetClient',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB0FSn8AalyOsUE5tHmRnXywyTA9xHpNvQ',
    appId: '1:100194839456:ios:85f3eefcc04d750af292c5',
    messagingSenderId: '100194839456',
    projectId: 'iste-528bd',
    storageBucket: 'iste-528bd.firebasestorage.app',
    iosBundleId: 'com.example.isteMbcetClient',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDZ5LY7J9dbhL7y3KPHI5hBOBW7ovLM3sU',
    appId: '1:100194839456:web:7686d913d8a7cf53f292c5',
    messagingSenderId: '100194839456',
    projectId: 'iste-528bd',
    authDomain: 'iste-528bd.firebaseapp.com',
    storageBucket: 'iste-528bd.firebasestorage.app',
  );
}
